### ISSUE TITLE
getting python exception error when running autopkg

### ISSUE THREAD

**Issue by KCH080208** [lindegroup/autopkgr#457] opened 2015-10-14 18:13 UTC
This is the error I get when running 

    A Python exception occurred during the execution of autopkg, see the system log for more details.
    [ERROR] AttributeError: '__NSCFDictionary' object has no attribute 'extend'

when running 

/usr/bin/python /usr/local/bin/autopkg run --recipe-list ~/Library/Application\ Support/AutoPkgr/recipe_list.txt --report-plist /tmp/autopkg-output.xml

i get the following

Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1660, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1654, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1420, in run_recipes
    search_github=make_suggestions)
  File "/usr/local/bin/autopkg", line 363, in load_recipe
    recipe["Process"].extend(child_recipe.get("Process", []))
AttributeError: '__NSCFDictionary' object has no attribute 'extend'

The only thing that has changed was an upgrade to 10.11 and then i upgraded to the latest of autopkgr.  I have since removed autopkgr and all add ins completely and reinstalled and still get this.   Any help would be greatly appreciated.

**Comment by eahrold** [comment] 2015-10-14 18:18
This is actually an autopkg issue. You should open up the issue there, they'll be able to better advise.
https://github.com/autopkg/autopkg/issues

In the meantime I'd start by looking at any new overrides you've created, or new recipe-repos you've added.

**Comment by homebysix** [comment] 2015-10-14 18:18
Hi @KCH080208,

Thanks for running `autopkg` in Terminal. That helps a lot. Because the error is still happening in Terminal outside of AutoPkgr, it's unlikely that this is a problem with AutoPkgr.

Instead, you may want to inspect the recipes included in your recipe_list.txt, especially any overrides that you have created. It looks like one of them may have its `Process` key set as a `dict` instead of an `array`.

I'd be happy to help you dig deeper if you post the recipe or override causing the problem, but I'm going to close this issue.

**Closed by homebysix** 2015-10-14 18:18 UTC

**Comment by KCH080208** [comment] 2015-10-14 18:20
This happens in autopkgr as well. I wasn't clear.  I ran that in terminal
to get a better view of the error.

**Comment by homebysix** [comment] 2015-10-15 00:24
Hi @KCH080208,

If the error occurs in Terminal, then it's not an AutoPkgr problem. It's likely that you've got a bad override.

You'll want to run the recipes in your recipe_list.txt one at a time and see which one causes the error, then inspect that recipe to see what the problem is. Look closely at the section that starts with `<key>Process</key>` and compare it to a working recipe, and I'm guessing it'll jump out at you.

**Comment by KCH080208** [comment] 2015-10-15 00:30
It had to be one of the repos. I also had to delete some prefs to.
Everything is working now.

**Comment by eahrold** [comment] 2015-10-15 01:15
Out of curiosity what prefs?

**Comment by KCH080208** [comment] 2015-10-15 01:23
I took a screen shot of it back at work. I can send it in tomorrow. But
what i think it was telling me in an error was that I still had a repo
selected that I really didn't.
