### ISSUE TITLE
Receiving an [ERROR] Import Error: No module named requests

### ISSUE THREAD

**Issue by chrodriguez1213** [lindegroup/autopkgr#607] opened 2018-01-05 16:13 UTC
Started to use AutoPkgr recently and installed JSSimporter (FYI, it works without JSSimporter but I want it to work with JSSimporter).  However, I get an error message when I try to run a recipe.  Please look at the following log:
----------------------------------------------------------------------------------------------------
(FULL AUTOPKG TRACEBACK) 
  File "/usr/local/bin/autopkg", line 36, in <module>

    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 629, in <module>

    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 532, in import_processors

    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/JSSImporter.py", line 29, in <module>

    import jss

  File "/Library/Application Support/JSSImporter/jss/__init__.py", line 62, in <module>

    from .jamf_software_server import JSS
  File "/Library/Application Support/JSSImporter/jss/jamf_software_server.py", line 33, in <module>

    from . import jssobjects
  File "/Library/Application Support/JSSImporter/jss/jssobjects.py", line 27, in <module>

    import requests

ImportError: No module named requests

**Comment by homebysix** [comment] 2018-01-06 04:59
This looks like a duplicate of https://github.com/lindegroup/autopkgr/issues/606. Please join the discussion over there. Thanks!

**Closed by homebysix** 2018-01-06 04:59 UTC
