### ISSUE TITLE
Port Test - Notifications tab - Does Not Auto Run

### ISSUE THREAD

**Issue by mikevmeyer** [lindegroup/autopkgr#531] opened 2016-05-18 18:02 UTC
I've noticed that the port test (green indicator) on the notifications tab does not auto-run, after the port settings have been previously set, and you open AutoPkgr preferences and navigate to that tab.  It currently appears as tho the port is not working even with a port number entered into it. Like the folders & integrations tab, where AutoPkgr auto checks integrations (i.e., JSS Importer, etc.)... I think that the port test should happen automatically, but it's not (at least that's what I would expect it to do). Instead, if I renter the value in the port text box, then hit enter, it then runs the port check.

**Comment by cgerke** [comment] 2016-06-03 03:01
Ditto.

**Comment by homebysix** [comment] 2016-06-03 16:29
@mikevmeyer @cgerke - I see where you're coming from. A green indicator means "this is working," and therefore if it's not green it must not be working.

However, what you're seeing is expected behavior, and AutoPkgr is behaving as it's meant to behave. Here's the normal order of operations:

1. The port field is selected and a value is entered.
2. The user "commits" the value by pressing Enter, Tab, or selecting another field.
3. That causes a port test to run, and the green or red indicator appears.

Navigating between tabs after a successful port test should maintain the green indicator, but closing and relaunching AutoPkgr will reset the indicator back to its default state — gray.

This is similar to the JSSImporter settings, where there's an indicator next to the Connect button that doesn't turn green until you click Connect, and subsequently returns to gray at next launch.

There are three possibilities that I see.

(a) After a successful test has been performed, save a record of that test to disk so that AutoPkgr can continue showing a green indicator at next launch. That seems to be what you're asking for. However, that's not ideal because disk operations slow the app down, and because a stored test result does not guarantee that the port is working right now at this moment.

(b) Automatically perform a port test every time a test indicator like this one is displayed, so that it's always accurate and up to date. That seems wasteful of network resources to me, and adds complexity to AutoPkgr.

(c) Add some kind of manual "Test" button, and require the user to click Test before the indicator is displayed. This takes something that was previously automatic and makes it manual, which I'm not a fan of.

None of those options appeal much to me, so I think we should leave it as-is.

Nods of agreement? Pitchforks of outrage?

**Comment by cgerke** [comment] 2016-06-03 23:32
Nods....just used to having a "Test" button in UI's

**Comment by mikevmeyer** [comment] 2016-06-06 17:48
@homebysix, I agree, full nods from me, leave as is.
I think some of this functionality stuff came into question when I was working with the email notification issues, but now that those are solved....

**Closed** 2016-06-06 17:57 UTC
Labels: question, wontfix
