### ISSUE TITLE
AutoPkgr 1.5.6 - forgets that Filewave Importer is installed

### ISSUE THREAD

**Issue by jaw4uz** [lindegroup/autopkgr#668] opened 2021-03-03 12:43 UTC
On previous versions,  the FilewaveImporter was installed and working. After updating to Autopkgr 1.5.6 the indicator shows that it is not installed. 
![Screen Shot 2021-03-03 at 7 35 51 AM](https://user-images.githubusercontent.com/5765212/109807313-b6424d80-7bf3-11eb-8d78-de5bf58f4bdc.png)

Clicking install returns this error message.
![Screen Shot 2021-03-03 at 7 36 23 AM](https://user-images.githubusercontent.com/5765212/109807275-a9255e80-7bf3-11eb-94a5-b133a9ae42c6.png)

I confirmed that the Filewave repo was present 
![Screen Shot 2021-03-03 at 7 37 09 AM](https://user-images.githubusercontent.com/5765212/109807435-e25dce80-7bf3-11eb-90eb-00deba479716.png)

**Comment by homebysix** [comment] 2021-03-03 18:12
Likely the same root cause as https://github.com/lindegroup/autopkgr/issues/665.

@jaw4uz, could you try replacing the `/Library/AutoPkg/autopkg` file with [this one](https://github.com/homebysix/autopkg/blob/expand-repo/Code/autopkg)? I've got a PR open and would like to confirm whether it solves the issue you're encountering.

**Comment by jaw4uz** [comment] 2021-03-03 19:03
@homebysix Replacing the autopkg file worked after replacing the file I clicked on install FilewaveImporter and it installed and now shows as active. Clicking Install VirusTotalAnalyzer installed it and now it shows as active. Right clicking on a git repo and clicking "Update this repo only" now works also.

**Comment by homebysix** [comment] 2021-03-03 19:47
Great, thank you for testing! I expect to release AutoPkg 2.3.1 tonight with the fix.

**Comment by jfuchtm** [comment] 2021-03-04 14:27
Does not appear that the 2.3.1 build resolved this.

**Comment by jfuchtm** [comment] 2021-03-04 14:29
Or I should say the FileWaveImporter still requires install everytime AutoPkgr is shutdown and reopened.

**Comment by homebysix** [comment] 2021-03-04 17:06
After discussing with @shawnhonsberger we determined there are two unrelated issues, which were both reported around the same time. AutoPkg 2.3.1 resolves #666, but does not resolve this one (#668).

**Comment by shawnhonsberger** [comment] 2021-03-05 17:11
Hi @jaw4uz and @jfucht. This should be resolved in today's 1.5.7 release. Thanks for your help and patience! https://github.com/lindegroup/autopkgr/releases/latest

**Comment by blackthroat** [comment] 2021-03-05 17:43
This is confirmed working for me now with 1.5.7. Thanks @shawnhonsberger!

**Closed** 2021-03-08 21:35 UTC
