### ISSUE TITLE
DMG Mount Errors and DMGs left mounted behind

### ISSUE THREAD

**Issue by majorsl** [lindegroup/autopkgr#563] opened 2016-10-12 22:08 UTC
I'm having an interesting issue since upgrading to Sierra.  I will randomly get failed runs claiming a recipe couldn't complete because the DMG couldn't be mounted, e.g.

com.github.autopkg.munki.Silverlight    Error in com.github.autopkg.munki.Silverlight: Processor: CodeSignatureVerifier: Error: /Volumes/Drobo/Storage/AutoPkg/Cache/com.github.autopkg.munki.Silverlight/downloads/Silverlight.dmg is not mounted
com.github.gerardkok.munki.calibre  Error in com.github.gerardkok.munki.calibre: Processor: CodeSignatureVerifier: Error: /Volumes/Drobo/Storage/AutoPkg/Cache/com.github.gerardkok.munki.calibre/downloads/Calibre.dmg is not mounted
com.github.autopkg.munki.AdobeReaderDC  Error in com.github.autopkg.munki.AdobeReaderDC: Processor: CodeSignatureVerifier: Error: /Volumes/Drobo/Storage/AutoPkg/Cache/com.github.autopkg.munki.AdobeReaderDC/downloads/AdobeReaderDC.dmg is not mounted

What is interesting is that each time this happens I find the dmg mounted in the Finder.  But, the next run can be completely normal with no issue. And these items exist in the cache, they've not been download since their last update (a few days ago for Silverlight and AdobeRaderDC and probably a couple of weeks since the last Calibre.

Try as I might, running these recipes "manually" with autopkg always seems to work okay.  I can't seem to make it fail that way.

**Comment by homebysix** [comment] 2016-10-12 22:44
I occasionally encounter this issue as well, either because I forgot to unmount a dmg after inspecting it, or because an AutoPkg run quit/crashed before the dmg could be unmounted. Subsequent runs will produce the "dmg is not mounted" error. The solution of manually unmounting the dmg and trying again seems to work for me.

I saw this issue on El Capitan too, but never often enough to make me think it was more than a one-off problem. Are you seeing these errors regularly?

I can reproduce the issue outside of AutoPkgr, like so:

1. Run a recipe that downloads a dmg.

    ```
    $ autopkg run -v Firefox.download
    Processing Firefox.download...
    MozillaURLProvider
    MozillaURLProvider: Found URL https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US
    URLDownloader
    URLDownloader: Storing new Last-Modified header: Fri, 23 Sep 2016 16:27:14 GMT
    URLDownloader: Storing new ETag header: "1480e8598aec3171cc8a91bbe060c6e3"
    URLDownloader: Downloaded ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/downloads/Firefox.dmg
    EndOfCheckPhase
    CodeSignatureVerifier
    CodeSignatureVerifier: Mounted disk image ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/downloads/Firefox.dmg
    CodeSignatureVerifier: Verifying application bundle signature...
    CodeSignatureVerifier: /private/tmp/dmg.QxwX2Y/Firefox.app: valid on disk
    CodeSignatureVerifier: /private/tmp/dmg.QxwX2Y/Firefox.app: satisfies its Designated Requirement
    CodeSignatureVerifier: /private/tmp/dmg.QxwX2Y/Firefox.app: explicit requirement satisfied
    CodeSignatureVerifier: Signature is valid
    Receipt written to ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/receipts/Firefox-receipt-20161012-154049.plist

    The following new items were downloaded:
        Download Path                                                                                           
        -------------                                                                                           
        ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/downloads/Firefox.dmg
    ```

2. Mount the dmg.

    ```
    $ open ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/downloads/Firefox.dmg
    ```

3. Run the same recipe again.

    ```
    $ autopkg run -v Firefox.download
    Processing Firefox.download...
    MozillaURLProvider
    MozillaURLProvider: Found URL https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US
    URLDownloader
    URLDownloader: Item at URL is unchanged.
    URLDownloader: Using existing ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/downloads/Firefox.dmg
    EndOfCheckPhase
    CodeSignatureVerifier
    ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/downloads/Firefox.dmg is not mounted
    Failed.
    Receipt written to ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/receipts/Firefox-receipt-20161012-154103.plist

    The following recipes failed:
        Firefox.download
            Error in com.github.autopkg.download.firefox-rc-en_US: Processor: CodeSignatureVerifier: Error: ~/Library/AutoPkg/Cache/com.github.autopkg.download.firefox-rc-en_US/downloads/Firefox.dmg is not mounted

    Nothing downloaded, packaged or imported.
    ```

**Comment by majorsl** [comment] 2016-10-14 22:26
Hi!  I saw it very, very randomly on El Capitan.  I did like you and ejected the DMGs and moved on.

I see it much more frequently with Sierra, although with some other things I see with this exceptionally buggy release, I'm temped to wait and see what 10.12.1 brings since a lot of my issues in other forums have reportedly been solved by users running the 10.12.1 betas.

**Comment by ITAtAnki** [comment] 2016-10-22 04:40
I'm having this problem reliably for a few recipes in my repo on my freshly upgraded Sierra autopkgr system. 

Looking through the logs, these errors pop out. It threw a sandboxing violation trying to unmount. 
default	21:23:30.925426 -0700	DiskUnmountWatcher	DiskUnmountWatcher: callback
default	21:23:30.962675 -0700	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	21:23:30.976748 -0700	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	21:23:30.978001 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:30.978108 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:30.978208 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:30.978282 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:30.978560 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:30.978642 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.012022 -0700	mds	directQueryFetchResultsReply 16385 1795162258 -1
default	21:23:31.025868 -0700	mds	directQueryFetchResultsReply 69633 1795162258 -1
default	21:23:31.042973 -0700	mds	directQueryFetchResultsReply 73731 1795162258 -1
default	21:23:31.043217 -0700	mds	directQueryFetchResultsReply 94209 1795162258 -1
default	21:23:31.109240 -0700	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	21:23:31.110716 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.110848 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.110953 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.111043 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.111386 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.111487 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.174499 -0700	mds	directQueryFetchResultsReply 94210 1795162258 -1
default	21:23:31.386024 -0700	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	21:23:31.387211 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.387319 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.387377 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.387433 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.387690 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.387747 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.547906 -0700	deleted	com.apple.activity_tracing.cache-delete: Successful Request
default	21:23:31.548009 -0700	deleted	com.apple.activity_tracing.cache-delete: Completion callback
default	21:23:31.548345 -0700	aslmanager	newConnection invalidated
default	21:23:31.548144 -0700	deleted	com.apple.activity_tracing.cache-delete took 1.559426 seconds, returned: <private>
default	21:23:31.548256 -0700	deleted	com.apple.activity_tracing.cache-delete updateInfo: <private>
default	21:23:31.548354 -0700	deleted	ENTRY, operation: CACHE_DELETE_PURGEABLE_OPERATION, serviceID: com.apple.activity_tracing.cache-delete info: <private>
default	21:23:31.548506 -0700	deleted	statfs <private>
error	21:23:31.548569 -0700	deleted	volRoot failed for <private>
default	21:23:31.548602 -0700	deleted	Connection to com.apple.activity_tracing.cache-delete was invalidated.
error	21:23:31.548625 -0700	deleted	unable to normalize volume: "<private>", tmp_result: (null)
error	21:23:31.548716 -0700	deleted	parameter error (volume). info: <private>
default	21:23:31.646352 -0700	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	21:23:31.647712 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.647832 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.647922 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.647997 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.648381 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.648486 -0700	authd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.700299 -0700	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	21:23:31.702169 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.702517 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.702654 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.702733 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.702932 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.703017 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.703096 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.703168 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.704168 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.704271 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.704397 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.704492 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.705126 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.705202 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.705273 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.706141 -0700	secinitd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	21:23:31.814918 -0700	deleted	completed calling plugIn beginUsing: for pid: 5517
default	21:23:31.818729 -0700	IDECacheDeleteAppExtension	in _willPerformHostCallback: block
default	21:23:31.819056 -0700	deleted	Connecting to <private>
error	21:23:31.825403 -0700	sandboxd	SandboxViolation: diskutil(5525) System Policy: deny file-ioctl /dev/rdisk0
Violation:       System Policy: deny file-ioctl /dev/rdisk0
Process:         diskutil [5525]
Path:            /usr/sbin/diskutil
Load Address:    0x109cf9000
Identifier:      diskutil
Version:         ??? (???)
Code Type:       x86_64 (Native)
Parent Process:  sh [5523]
Responsible:     /Applications/Server.app/Contents/ServerRoot/usr/libexec/smartmonitor.sh [5513]
User ID:         0

Date/Time:       2016-10-21 21:23:31.302 PDT
OS Version:      Mac OS X 10.12 (16A323)
Report Version:  8

Thread 0 (id: 56084):
0   libsystem_kernel.dylib        	0x00007fffd64c4686 __ioctl + 10
1   DiskManagement                	0x00007fffcd2718f7 _DMwholeDiskSupportsLowLevelFormat + 166
2   DiskManagement                	0x00007fffcd27d39e -[DMManager(Info) wholeDiskSupportsLowLevelFormat:error:] + 180
3   diskutil                      	0x0000000109d050b2
4   diskutil                      	0x0000000109cff7f5
5   diskutil                      	0x0000000109cff202
6   diskutil                      	0x0000000109cfa877
7   Foundation                    	0x00007fffc2d4bc88 __NSFireDelayedPerform + 417
8   CoreFoundation                	0x00007fffc12cdf44 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
9   CoreFoundation                	0x00007fffc12cdbd3 __CFRunLoopDoTimer + 1075
10  CoreFoundation                	0x00007fffc12cd72a __CFRunLoopDoTimers + 298
11  CoreFoundation                	0x00007fffc12c52f1 __CFRunLoopRun + 2081
12  CoreFoundation                	0x00007fffc12c4874 CFRunLoopRunSpecific + 420
13  Foundation                    	0x00007fffc2ce0cb2 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 277
14  Foundation                    	0x00007fffc2ce0b8a -[NSRunLoop(NSRunLoop) run] + 76
15  diskutil                      	0x0000000109cfa7e4
16  diskutil                      	0x0000000109cfa8d5
17  libdyld.dylib                 	0x00007fffd6396255 start + 1
18  diskutil                      	0x0000000000000003

Thread 1 (id: 56099):
0   libsystem_kernel.dylib        	0x00007fffd64c54e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffd65ac221 start_wqthread + 13

Thread 2 (id: 56100):
0   libsystem_kernel.dylib        	0x00007fffd64c54e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffd65ac221 start_wqthread + 13

Thread 3 (id: 56101):
0   libsystem_kernel.dylib        	0x00007fffd64c54e6 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fffd65ac221 start_wqthread + 13

Binary Images:
       0x109cf9000 -        0x109d3fff3  diskutil (1054) <b31f0e19-fca2-36a8-8de5-bc57fee2320f> /usr/sbin/diskutil
    0x7fffc1240000 -     0x7fffc16d3ff7  com.apple.CoreFoundation (6.9 - 1348.1) <2a35be4f-ba5b-3c22-bcf1-cfbba2786081> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fffc2cbe000 -     0x7fffc3065ffb  com.apple.Foundation (6.9 - 1349) <08a463b1-296e-3ac1-b8d3-01a75b0785a8> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fffcd24f000 -     0x7fffcd2b1ff7  com.apple.DiskManagement (9.0 - 1054) <191b21aa-7bae-3175-b94e-a921d86e9327> /System/Library/PrivateFrameworks/DiskManagement.framework/Versions/A/DiskManagement
    0x7fffd6391000 -     0x7fffd6396ff3  libdyld.dylib (421.1) <cdfbdc9c-418c-369d-b433-f64b0630e640> /usr/lib/system/libdyld.dylib
    0x7fffd64ab000 -     0x7fffd64cdff7  libsystem_kernel.dylib (3789.1.32) <5c68a0d7-c3c9-3e52-b983-ede9a28ab6fc> /usr/lib/system/libsystem_kernel.dylib
    0x7fffd65a9000 -     0x7fffd65b3fff  libsystem_pthread.dylib (218.1.3) <050ae77b-4f4b-334a-a5ba-cf0d10af5304> /usr/lib/system/libsystem_pthread.dylib
default	21:23:31.943249 -0700	diskimages-helper	*** -[NSMachPort handlePortMessage:]: dropping incoming DO message because the connection is invalid
default	21:23:32.094323 -0700	AutoPkgr	Receipt written to /Users/ankicore/Library/AutoPkg/Cache/local.munki.Anki-GoogleEarth/receipts/local.munki-receipt-20161021-212332.plist
default	21:23:32.665050 -0700	accountsd	__48-[ACDServer listener:shouldAcceptNewConnection:]_block_invoke.206 (482) "Idle-exit-preventing transaction ended!"
default	21:23:32.699502 -0700	AutoPkgr	Processing MakeCatalogs.munki...
default	21:23:32.699857 -0700	AutoPkgr	Run status: Processing MakeCatalogs.munki...
default	21:23:32.708643 -0700	AutoPkgr	MakeCatalogsProcessor
default	21:23:32.710757 -0700	AutoPkgr	MakeCatalogsProcessor: No need to rebuild catalogs.
default	21:23:32.715257 -0700	AutoPkgr	Receipt written to /Users/ankicore/Library/AutoPkg/Cache/com.github.autopkg.munki.makecatalogs/receipts/MakeCatalogs-receipt-20161021-212332.plist

The following recipes failed:
    local.munki.Anki-GoogleEarth
        Error in local.munki.Anki-GoogleEarth: Processor: CodeSignatureVerifier: Error: /Users/ankicore/Library/AutoPkg/Cache/local.munki.Anki-GoogleEarth/downloads/GoogleEarth.dmg is not mounted
default	21:23:32.716171 -0700	AutoPkgr	
Nothing downloaded, packaged or imported.
default	21:23:32.755900 -0700	AutoPkgr	
Report plist saved to /var/folders/nk/7g0h0zt17jz3bpf7hrm1fr5r0000gn/T/com.lindegroup.AutoPkgr/20161021212107.
default	21:23:32.931365 -0700	AutoPkgr	Error [1] Error running recipes 
 /Users/ankicore/Library/AutoPkg/Cache/local.munki.Anki-GoogleEarth/downloads/GoogleEarth.dmg is not mounted

**Comment by majorsl** [comment] 2016-10-27 22:16
I'm still seeing it even after the 10.12.1 update.

**Comment by homebysix** [comment] 2016-10-27 22:59
Yeah, that's annoying. I've seen it intermittently as well. I can't say for sure whether AutoPkgr is involved, though, until somebody who's *not* using AutoPkgr weighs in.

Maybe I'll run my recipes using [autopkgd](https://github.com/groob/autopkgd) for a week or two, and see whether the error returns.

**Comment by danner26** [comment] 2016-12-23 01:43
I have been racking my brain on this for a while. It seems (on multiple machines) the recipes work for multiple days. Then out of the blue (I cannot find a pattern) I get these errors. This happens with overridden and standard munki recipes.

I have uninstalled, cleaned and reinstalled autopkg to no avail (including recipe repos). I have rebuilt autopkg using the latest installer also which did not help. When I navigate to the dmg path, it allows me to mount and execute it. The other issue is for some packages, it errors out during the hdiutil decoding I believe? 2 output snippets are below.

```
fsmacserv:~ administrator$ Autopkg run -v Dropbox.munki
Processing Dropbox.munki...
URLDownloader
URLDownloader: File size returned by webserver matches that of the cached file: 95047858 bytes
URLDownloader: WARNING: Matching a download by filesize is a fallback mechanism that does not guarantee that a build is unchanged.
URLDownloader: Using existing /Users/administrator/Library/AutoPkg/Cache/local.munki.Dropbox/downloads/Dropbox.dmg
EndOfCheckPhase
CodeSignatureVerifier
/Users/administrator/Library/AutoPkg/Cache/local.munki.Dropbox/downloads/Dropbox.dmg is not mounted
Failed.
Receipt written to /Users/administrator/Library/AutoPkg/Cache/local.munki.Dropbox/receipts/Dropbox-receipt-20161222-204119.plist

The following recipes failed:
    Dropbox.munki
        Error in local.munki.Dropbox: Processor: CodeSignatureVerifier: Error: /Users/administrator/Library/AutoPkg/Cache/local.munki.Dropbox/downloads/Dropbox.dmg is not mounted

Nothing downloaded, packaged or imported.
```
```
fsmacserv:~ administrator$ autopkg run -v GoogleChrome.munki
Processing GoogleChrome.munki...
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/administrator/Library/AutoPkg/Cache/local.munki.GoogleChrome/downloads/GoogleChrome.dmg
EndOfCheckPhase
MunkiImporter
MunkiImporter: Traceback (most recent call last):
MunkiImporter:   File "/usr/local/munki/makepkginfo", line 1166, in <module>
MunkiImporter:     main()
MunkiImporter:   File "/usr/local/munki/makepkginfo", line 847, in main
MunkiImporter:     if munkicommon.DMGisWritable(item):
MunkiImporter:   File "/usr/local/munki/munkilib/munkicommon.py", line 856, in DMGisWritable
MunkiImporter:     'hdiutil error %s with image %s.' % (err, dmgpath))
MunkiImporter: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 192: ordinal not in range(128)
creating pkginfo for /Users/administrator/Library/AutoPkg/Cache/local.munki.GoogleChrome/downloads/GoogleChrome.dmg failed: Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 1166, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 847, in main
    if munkicommon.DMGisWritable(item):
  File "/usr/local/munki/munkilib/munkicommon.py", line 856, in DMGisWritable
    'hdiutil error %s with image %s.' % (err, dmgpath))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 192: ordinal not in range(128)

Failed.
Receipt written to /Users/administrator/Library/AutoPkg/Cache/local.munki.GoogleChrome/receipts/GoogleChrome-receipt-20161222-204124.plist

The following recipes failed:
    GoogleChrome.munki
        Error in local.munki.GoogleChrome: Processor: MunkiImporter: Error: creating pkginfo for /Users/administrator/Library/AutoPkg/Cache/local.munki.GoogleChrome/downloads/GoogleChrome.dmg failed: Traceback (most recent call last):
          File "/usr/local/munki/makepkginfo", line 1166, in <module>
            main()
          File "/usr/local/munki/makepkginfo", line 847, in main
            if munkicommon.DMGisWritable(item):
          File "/usr/local/munki/munkilib/munkicommon.py", line 856, in DMGisWritable
            'hdiutil error %s with image %s.' % (err, dmgpath))
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 192: ordinal not in range(128)

Nothing downloaded, packaged or imported.
fsmacserv:~ administrator$ 
```

**Comment by trademarkable** [comment] 2018-03-21 22:56
I'm "happy" to say I can turn this error (and the ordinal not in range error in #563 closed as external) on and off at will…with Time Machine. 

It's an autopkg bug, not AutoPkgr, or I'm missing something obvious. I love me some AutoPkgr, but I almost always run autopkg recipes at the command line because I'm OCD like that. Anyhoo, 100% reproducible with the following setup:

Mount a remote Time Machine backup disk for my Sierra 10.12.6 OS X Server by choosing "back up now" from the menu bar item. Wait a few seconds for the network volume to be mounted and the backup to begin.

Run an autopkg recipe. Any existing autopkg recipe will now fail with either the ordinal not in range error (in my case, seemingly anything with a hyphen in the dmg name) or the 'not mounted' error above. Stop the backup, wait for the Time Machine volume to be unmounted, and the recipes which failed a minute ago will work just fine. No clearing the cache, no further troubleshooting needed.

I haven't tested whether this is a condition that causes the errors when it's a remote smb volume other than a Time Machine volume, and I haven't tested to see if this condition passes if you let Time Machine run for a few minutes before running any autopkg recipe. 

If I were to try to solve this bug for autopkg I'd start by taking a look at the assumptions autopkg makes about mounting disks / disk images while hdutil (or whatever the underlying tool is) is already working for Time Machine–or how it deals with multiple volumes mounted at the same time. Is it timing out, or looking for the first mounted non-boot volume (which is Time Machine, not a recipe's dmg, when Time Machine is running). Just a hunch so far. I'm looking forward to having time to solve this one…someday.

Mark

PS: Anyone running this on High Sierra? Same bug?

**Comment by shawnhonsberger** [comment] 2019-09-16 21:08
This is a known issue in AutoPkg, in new versions of macOS as well.

**Closed by shawnhonsberger** 2019-09-16 21:08 UTC
