### ISSUE TITLE
Chrome causes Autopkgr to hang at "Run AutoPkg Now"

### ISSUE THREAD

**Issue by kylevitale** [lindegroup/autopkgr#230] opened 2014-12-04 17:59 UTC
Autopkgr no longer runs for me and I am not sure why. When I run it I get the "Running selected Autopkg updates" status but no updates are ever process, nor does this window ever mention that recipes were processed. In the past I would see the update currently being processed such as "puppet.munki 2/12" or something similar. Now the message never changes and I have to force quit autopkgr.

I have tried deleting all known files from caches, prefs, app support, saved states, etc (not sure if I found them all) but I still can't get it to run.

Running autopkg from command line works just fine.

I enabled Verbose logs but nothing shows up there. It just stalls.

Any idea where I can go from here?

**Comment by kylevitale** [comment] 2015-01-05 17:09
Anything else you wish for me to try?

**Comment by eahrold** [comment] 2015-01-05 17:44
@kylevitale, thanks for offering. I've put up yet another build that actually removes environment settings from the NSTask backend (this may be where settings are getting injected). I'd love to know if this helps at all. Thanks.

https://github.com/eahrold/autopkgr/releases/tag/v1.2-beta3

**Comment by kylevitale** [comment] 2015-01-05 17:45
The last link posted to 1.2-beta3 is broken for me. Is that what you are
referencing?

**Comment by eahrold** [comment] 2015-01-05 18:18
Dooh, here it is...
https://github.com/eahrold/autopkgr/releases/tag/v1.2-beta3-a

And in general all of my testing builds go up here...
https://github.com/eahrold/autopkgr/releases

**Comment by gerardweese** [comment] 2015-01-05 18:43
@eahrold I have tested the newest beta and the result is no different. I still have the same Chrome tabs open from last week. I could try and closing all of them, and chrome , re-opening them from history and seeing if I can reproduce it. 

below is an image of what I get with the build number. 
http://cl.ly/image/2D1y3r3a2t2C

-Gerard

**Comment by eahrold** [comment] 2015-01-05 19:15
@gerardweese Thanks for checking. That build number isn't accurate, I didn't update that when I but up the testing build.

If you could try closing, re-opening one by one, and seeing if a particular one is responsible let me know what the url is, it may help me reproduce. 

If I could just make it happen on my machine, I'm pretty sure I could figure out a way to squash it.

Thanks again for your help.

**Comment by eahrold** [comment] 2015-01-05 21:18
You can cancel from the beta build correct?

**Comment by gerardweese** [comment] 2015-01-05 21:34
Yes, cancel works in the v1.2-beta3-a release but not in the current 1.1.3

**Comment by kylevitale** [comment] 2015-01-06 00:50
I can confirm the same as @gerardweese. I cannot point to a specific tab,
but closing a second account window usually does the trick to get autopkgr
working.

Cancel does work in this beta, which is new.

On Monday, January 5, 2015, gerardweese <notifications@github.com> wrote:

> Yes, cancel works in the v1.2-beta3-a release but not in the current 1.1.3
>
> On Mon, Jan 5, 2015 at 1:18 PM, Eldon Ahrold <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > You can cancel from the beta build correct?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/lindegroup/autopkgr/issues/230#issuecomment-68783151>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lindegroup/autopkgr/issues/230#issuecomment-68785848>.
>


-- 
Sent from my mobile

**Comment by ToddToddTodd** [comment] 2015-01-07 19:21
I'm experiencing the same issue. I'm running Chrome Version 39.0.2171.95 (64-bit) & AutoPkgr 1.1.3 (589). I'm trying AutoPkgr 1.2-alpha (560) and it still hangs at "Running selected AutoPkg recipes.", but I'm now able to cancel the dialog box.

**Comment by eahrold** [comment] 2015-01-07 20:34
@ToddToddTodd, and closing chrome fixes it for you too?

**Comment by eahrold** [comment] 2015-01-07 20:45
@gerardweese, @kylevitale, @ToddToddTodd 
Do you experience the same hanging when pressing "Update Repos Now" or is it just on "Check Apps Now"?

**Comment by gerardweese** [comment] 2015-01-07 21:55
@eahrold I have only seen it on "Check Apps."

**Comment by kylevitale** [comment] 2015-01-08 01:47
@eahrold <https://github.com/eahrold> Only on "Check Apps Now", "Update
Repos Now" has never given me an issue.

**Comment by eahrold** [comment] 2015-01-08 03:52
@kylevitale, @gerardweese ...

So I've reworked some more things to hopefully address this. 
https://github.com/eahrold/autopkgr/releases/tag/v1.2-beta-ec

There are two separate versions here, one that forces python to run in i386 mode and one that forces it to run in x86_64. Pleas try both and see if either work.

It also changes the way the file handles that provide progress updates are setup. I saw that cause a similar issue in another situation. 

Thanks again,

--Eldon

**Comment by ToddToddTodd** [comment] 2015-01-08 17:31
@eahrold Closing Chrome does fix the issue

**Comment by gerardweese** [comment] 2015-01-12 19:18
@eahrold I'm sorry to report the issue still exists on both versions. Since we now have an option to cancel and we know a simple work around of closing Chrome I'm willing to move on.

**Comment by homebysix** [comment] 2015-02-06 18:22
@gerardweese Could you test again on the latest beta 1.2-rc1? Just want to see if the behavior remains consistent.

**Comment by gerardweese** [comment] 2015-02-07 08:37
Sure, I will take a look on Monday; I have been running the 1.2 beta for a month I will try the rc.




-Gerard



—

**Comment by homebysix** [comment] 2015-02-13 19:21
@gerardweese 1.2 final release is out now.

**Comment by gerardweese** [comment] 2015-03-10 00:39
@homebysix this is still an issue. I can still work around it by closing Chrome, and the cancel button works. Not a huge source of pain.

**Comment by kylevitale** [comment] 2015-03-10 01:31
It hasn't been happening for me.

**Comment by da4ftso** [comment] 2015-03-17 16:21
Still happens for me.  AutoPkgr 1.2.1 (726) on 10.9.5 w/ latest Chrome 41.

**Comment by ToddToddTodd** [comment] 2015-03-17 22:58
It's still happening for me on AutoPkgr Version 1.2.1 (726) & OS 10.10.2 & Chrome 41.0.2272.89 (64-bit)

**Comment by eahrold** [comment] 2015-04-29 19:13
@homebysix, 
So I was thinking about what could have been causing your schedule run to hang as you mentioned in https://github.com/lindegroup/autopkgr/issues/340#issuecomment-97130979, and I suspect that it may be another side effect of this issue.

The AutoPkg(r) runInBackground could also stall the same way that "Run AutoPkg Now" does. If that occurred launchd wouldn't run the job on it's subsequent schedule since the previous run never exited.

I've got two ideas as to how to deal with this.
1 - during the main background execution, check if there is an active `/Applications/AutoPkgr.app/Contents/MacOS/AutoPkgr -runInBackground YES` process running and if so, kill that process. A kill signal would automatically cause launchd to respawn the process.

2 - Add a similar check in the LGAutoPkgTask that acts as a timeout timer and if the actual `/usr/local/bin/autopkg run ...` isn't processing within a second or two call the completion block error.

I'm pretty sure the first would work and it's something I could test.

The second has the benefit of addressing both background runs and "Run AutoPkg Now" as well as sending back an error, but since I haven't been able to reproduce this situation it'd be another stab in the dark as to it's actual functioning.

Are you able to replicate this with any regularity? If so I'll start putting up some builds, and we can test out some of these techniques.

Thoughts?

And @da4ftso , @ToddToddTodd , @gerardweese 
Next time this happens would you mind taking a sample
`/usr/bin/sample AutoPkgr`
and posting a link to a [gist](http://gist.github.com) here with the contents.
Thanks.

**Comment by homebysix** [comment] 2015-04-30 18:09
@eahrold Chrome is starting to block AutoPkgr pretty regularly lately. I've tried closing one tab at a time and re-running to see if it's related to a particular tab or website, but the problem persists even if Chrome doesn't have any windows open at all.

Feel free to branch/build and I'll test.

**Comment by eahrold** [comment] 2015-05-01 13:59
@kylevitale, @ToddToddTodd , @gerardweese , @da4ftso , @jhowe-sgs, @jumpkick, @Tecnico1931

Good news! I thing we got this fixed. 
If you're interested in trying out a testing version out please grab this...
https://dl.dropboxusercontent.com/u/120270/AutoPkgr/AutoPkgr-ChromeFix.dmg

Long story short, we currently thing the problem wasn't Google Chrome's injecting anything into python or autopkgr as we initially suspected, but rather it's unusual practice of creating so many "Goolge Chrome Helper" processes each with such astoundingly long launch arguments. (just run `ps -e -o command= > /tmp/ps_dump.txt` and you'll see just how massive each helper launch invocation is)

Ultimately this was causing the stdout buffer of the NSTask to fill up and wait to be flushed, resulting in a the stall.

We would love your feedback and help testing out this new version.
Thanks.

**Comment by homebysix** [comment] 2015-05-01 15:15
Nice job @eahrold! This was such an annoying bug. Glad that it's squashed!

**Closed** 2015-05-08 15:43 UTC
Labels: bug, close-imminent, help wanted
