### ISSUE TITLE
Slack Notification not sent for software imported into Munki if option is selected

### ISSUE THREAD

**Issue by kevinmcox** [lindegroup/autopkgr#634] opened 2019-12-13 19:04 UTC
It appears that Slack notifications will not be sent when software is imported into Munki if the option "_New software imported to Munki, JSS, or other server_" is selected at all. (This does not effect other notifications sent at the same time such as downloads, errors, etc. Examples below showing one Slack message with the import notification and another without. )

![AutoPkgr notificaitons](https://user-images.githubusercontent.com/25358601/70824791-9af9e100-1da8-11ea-8781-7f470b861f4e.png)

This includes when the selected preference is "_Any action_" but the specific box remains checked (but greyed out) below:

![Any Action but selected](https://user-images.githubusercontent.com/25358601/70824635-3c346780-1da8-11ea-9578-28cd734a7e4f.png)

It also includes when the selected preference is "_Selected actions_" and includes the "_New software imported to Munki, JSS, or other server_" option:

![Selected](https://user-images.githubusercontent.com/25358601/70824649-40f91b80-1da8-11ea-919b-9054bb720dd2.png)

If "_Any action_" is selected and the "_New software imported to Munki, JSS, or other server_" option is not checked then the import notification is sent:

![Any action no selections](https://user-images.githubusercontent.com/25358601/70824658-45253900-1da8-11ea-9435-8bbf5dc28e50.png)

I haven't noticed any of the other notification options being similarly effected, but haven't tested for them either. Please let me know if you have any questions or need additional clarifications.

**Comment by shawnhonsberger** [comment] 2020-02-07 16:56
Thanks for this. I am not actually able to reproduce it. Are you able to reproduce this on a fresh vm, or a system with a fresh install?

**Comment by mikethehill** [comment] 2020-02-07 17:43
I can reproduce this on a 10.14.6 (fully patched) VM, with a fresh install of Munki 4.0.1.3899, Autopkg 2.0.2, Git 2.2.1 and Autopkgr 1.5.2. 

Autopkgr can successfully send a test message to Slack and also send test template messages, but no notifications are sent during an autopkg run (irrespective of whether I have all items individually checked or if they're all un-checked and 'Any action' is selected). 

I see the same behaviour on our prod Munki/Autopkg(r) box. Please let me know if you need anything further!

**Comment by shawnhonsberger** [comment] 2020-02-14 00:19
Thank you. If you select **Selected Actions > New software imported to Munki, JSS, or other server** you notice any Slack-related errors in the log when you run a recipe?

**Comment by mikethehill** [comment] 2020-02-14 20:36
No, not that I can see under the autpkgr process (comparing log entries from a test message and an AutoPkgr run).

Attached are the output from a 'send test' under Slack notification configuration screen (SlackTest.txt) and a sample AutoPkgr run to fetch Chrome (AutoPkgr_run.txt). Verbose logging is turned on for both of these.  

Hope this is useful!

`
[SlackTest.txt](https://github.com/lindegroup/autopkgr/files/4206665/SlackTest.txt)
[AutoPkgr_run.txt](https://github.com/lindegroup/autopkgr/files/4206666/AutoPkgr_run.txt)

`

**Comment by shawnhonsberger** [comment] 2020-02-25 22:04
@kevinmcox @mikethehill was this working before December? Is that when it started?

**Comment by mikethehill** [comment] 2020-02-26 21:16
Unable to say re: working before December as I've only recently looked at AutoPkgr (starting with 1.5.1). Just tested this with AutoPkgr 1.5 (running autopkg 1.4.1) and I get the same result - test notifications are successfully sent, along with message template test message, but nothing after an AutoPkg run.

**Comment by kevinmcox** [comment] 2020-02-26 23:33
@mikethehill, thanks so much for jumping in here while I was away and confirming the issue.

@shawnhonsberger, I can't say when it started. I only noticed because I was setting up a new Autopkg computer and was setting everything back up from scratch.

I was able to confirm it on both my old (physical server) and new setup (VM) if I manipulated the settings as shown in the screenshots above.

**Comment by mikethehill** [comment] 2020-03-27 15:48
@kevinmcox Do Slack notifications work if you enable email alerts? I enabled email alerts, left Slack alerts enabled, ran recipes and received both an email alert and Slack!

**Comment by kevinmcox** [comment] 2020-03-27 16:27
Yep, if I turn on email notifications it fixes the specific issue with the checkbox.

**Comment by shawnhonsberger** [comment] 2020-05-26 20:16
@kevinmcox I have been testing this with AutoPkgr 1.5.3 with, and without email notifications enabled and I am able to get Slack Notifications. Here is a picture of my settings that work for me. Is this still an issue for you? 
![Screen Shot 2020-05-26 at 7 58 31 AM](https://user-images.githubusercontent.com/20520337/82946400-24fec600-9f53-11ea-94dc-c790d6a5479d.png)

**Comment by kevinmcox** [comment] 2020-05-26 20:29
@shawnhonsberger I had just left emails on. I'll switch the settings around and test again with 1.5.3.

**Comment by shawnhonsberger** [comment] 2020-05-26 21:02
Thanks, @kevinmcox!

**Comment by kevinmcox** [comment] 2020-05-27 16:23
@shawnhonsberger Unfortunately I'm seeing the same behavior. I just spent an hour testing all the variations and there is no change from my original post.

With the settings in your last screenshot I get the Slack notification, but only related to the download, not the import into Munki (like my very first screenshot at the top). Enabling email alerts sends both parts of the notification to Slack.

**Comment by shawnhonsberger** [comment] 2020-07-28 22:31
@kevinmcox Thanks for confirming. Though I am unable to reproduce it, it doesn't mean I don't want to chase this down. If you are fine leaving email notifications on, then we'll leave it be.

**Comment by kevinmcox** [comment] 2020-08-02 21:07
No worries Shawn. I don't even need to leave email notifications on, as long as I have things set like this it works:

https://user-images.githubusercontent.com/25358601/70824658-45253900-1da8-11ea-9435-8bbf5dc28e50.png

**Comment by shawnhonsberger** [comment] 2020-08-05 16:31
Thank you, @kevinmcox. I'll close this for now. In the meantime, I'll keep watching for it and I'll also take a look at the button next chance I get.

**Closed by shawnhonsberger** 2020-08-05 16:31 UTC

**Comment by Prodeguerriero** [comment] 2020-09-09 10:09
@shawnhonsberger FYI, I see similar behaviors. I don't think opening a new issue makes sense, so I will write my report here.

The persistence of the notifications settings seem to be a tad inconsistent across the board.
On my clean install on Catalina, I experience the following:

- Slack and macOS notifications don't fire if email notifications are disabled.
  The moment I turn email notifications back on, the others start working again. I cannot troubleshoot any further because the log isn't verbose enough to do so.
  Note: I enabled `Verbose logs` and `Verbose AutoPkg run`.

- Notification trigger rules are not overridden by the `Any action`. E.g.:
  1. Choose `Selected actions`, and remove `New software is downloaded`.
  2. Choose `Any action` and close.

  One would expect to be notified about new downloads, but it doesn't seem to be the case. It looks like the `Any action` selection is not being registered. Restarting AutoPkgr doesn't seem to solve the problem.

Cheers!
