### ISSUE TITLE
UnicodeEncodeError on every run

### ISSUE THREAD

**Issue by zackbennis** [lindegroup/autopkgr#360] opened 2015-05-18 13:55 UTC
Every time I run autopkgr, I get the following error:

    A Python exception occurred during the execution of autopkg, see the system log for more details.
    [ERROR] : 'ascii' codec can't encode character u'\u2019' in position 143: ordinal not in range(128)

I have checked and double checked my recipes to make sure there's nothing in there causing the issue, and have taken to disabling all recipes except one that I know is fine. Still getting an error. Here's is the more verbose log:

    5/18/15 9:35:15.643 AM AutoPkgr[80595]: (FULL AUTOPKG TRACEBACK)
    File "/usr/local/bin/autopkg", line 1469, in <module>`
    
    `sys.exit(main(sys.argv))`
    File "/usr/local/bin/autopkg", line 1463, in main`
    
    exit(subcommands[verb]['function'](argv))
    File "/usr/local/bin/autopkg", line 1249, in run_recipes
    
    options.postprocessors)
    File "/usr/local/bin/autopkg", line 214, in load_recipe
    
    name, override_dirs + recipe_dirs)
    File "/Library/AutoPkg/autopkglib/__init__.py", line 138, in find_recipe_by_identifier

    if get_identifer_from_recipe_file(match) == identifier:
    File "/Library/AutoPkg/autopkglib/__init__.py", line 121, in get_identifer_from_recipe_file
    
    "WARNING: plist error for %s: %s" % (filename, unicode(err)))
    UnicodeEncodeError
    : 'ascii' codec can't encode character u'\u2019' in position 154: ordinal not in range(128)

This started happening when I upgraded to 1.2.3. I've tried uninstalling, but that seems to preserve a whole bunch of settings that could be causing trouble. If there's a straightforward way to remove everything and start from scratch, I would be more than happy to do that.

Thanks!

**Comment by eahrold** [comment] 2015-05-18 16:18
Nope, it's a known issue with autopkg and must have been incidental when upgrading to AutoPkgr 1.2.3

See this for a fix. https://github.com/lindegroup/autopkgr/issues/293
I'm trying to figure out if there's a way we can solve it with AutoPkgr, and will post updates on that thread.

**Comment by tincansandtwine** [comment] 2015-05-18 17:35
Thanks, eahrold. I tried the fix you listed without success. Still got the same error.

As it turns out, I had some errant characters in a recipe override I wasn't even using, which was still causing the error. Is this expected behavior?

**Comment by eahrold** [comment] 2015-05-18 17:43
It could. I think autopkg is iterating through all available recipes and overrides and when it hits one of those characters the exception is raised.

I can't be sure, but also check and make sure none of your file names have a similar character.

in a shell, if you do `env` what do you have for the `__CF_USER_TEXT_ENCODING` and `LANG` keys?

**Comment by tincansandtwine** [comment] 2015-05-18 18:08
I get `LANG=en_US.UTF-8` and `__CF_USER_TEXT_ENCODING` isn't in the list.

**Comment by eahrold** [comment] 2015-07-20 16:44
@tincansandtwine, not sure if you ever figured this out, if not try looking for any "Smart Quotes" in your recipe overrides, and replace them with standard quotes (Depending on your editor you may need to disable the SQ feature).

also see #380

**Comment by homebysix** [comment] 2015-07-24 17:22
Closing this, but @tincansandtwine please do re-open if it's still happening after you upgrade to 1.3, which will be available later today.

**Comment by zackbennis** [comment] 2016-09-01 12:48
Per [this](https://github.com/autopkg/autopkg/issues/111#issuecomment-243581389) conversation, it looks like this error occurs when autopkg runs into an issue with a recipe, and AutoPkgr tries to read the error message that autopkg ran into, which contains a curly quote. This breaks the Autopkgr. Ideally, the message from autopkg could be forwarded, because it contains exactly which recipe has the issue.

**Comment by homebysix** [comment] 2016-10-18 16:42
I'm going to close this issue, because I think we've established that a badly formatted recipe or override can cause this error to happen. One such recipe currently exists in the tallfunnyjew-recipes recpository, and should be fixed by [this PR](https://github.com/autopkg/tallfunnyjew-recipes/pull/7).

I'm going to open a new issue for the meta-error itself, because AutoPkgr should be able to pass more useful information about the root cause of this issue in the first place.

**Closed by homebysix** 2016-10-18 16:42 UTC
Labels: duplicate
