### ISSUE TITLE
Getting non valid error messages

### ISSUE THREAD

**Issue by Bretterteig** [lindegroup/autopkgr#697] opened 2023-01-09 11:05 UTC
When I run a recipe (local override) manually I am shown a local trust verification error after execution no matter what.

The recipe completes successfully and is able to package/import new software. I attached a sample screenshot of the error.

<img width="1337" alt="Screenshot 2023-01-09 at 11 57 14" src="https://user-images.githubusercontent.com/47298401/211294087-cc23a09d-6ca9-474a-b84b-af81f56b30ef.png">

Environment:
* Intel based Mac Mini
* Ventura 13.1
* Latest Munki 6.x and AutoPkg 2.7.2
* Munki repo is on an external drive

**Comment by shawnhonsberger** [comment] 2023-01-09 16:24
Thanks @Bretterteig. Have you tried updating your trust info on your Make Catalogs recipe override? If you are not using an override for Make Catalogs, it is recommended. Please let me know how it goes once you've updated your trust into on Make Catalogs.

**Comment by Bretterteig** [comment] 2023-01-09 17:05
Hey @shawnhonsberger,

I was able to create an override for MakeCatalogs but could not add it to the active recipe list.
After the override was created the error went away. 

Care to elaborate a bit?

**Comment by shawnhonsberger** [comment] 2023-01-09 17:14
Thank you @Bretterteig. This is in the recommended setup steps for Munki in the [Wiki](https://github.com/lindegroup/autopkgr/wiki/Munki). You only need to create that override once. AutoPkgr will automatically add the MakeCatalogs.munki recipe to the end of your recipe list and keep it there. You do not have to check the box to include the MakeCatalogs.munki in your schedule. It will be included automatically. The reason for that is that AutoPkgr runs the MakeCatalogs.munki recipe after a recipe run, this is by design.

**Closed by shawnhonsberger** 2023-01-09 17:14 UTC
