### ISSUE TITLE
Email notifications changed after 1.4 update

### ISSUE THREAD

**Issue by chilcote** [lindegroup/autopkgr#508] opened 2016-03-10 22:43 UTC
After the 1.4 update, the email notifications have a few issues:

![screen_shot_2016-03-10_at_2_38_23_pm](https://cloud.githubusercontent.com/assets/305026/13687120/54f572b0-e6ce-11e5-8924-46d9c18f5c68.png)

1. It's reporting older packages that have already been downloaded.
2. It's not reporting any of the changes to the JSS via the importer.

**Comment by homebysix** [comment] 2016-03-10 22:48
Hi @chilcote.

Could you try something? Download [this raw file](https://gist.githubusercontent.com/homebysix/452d9ad78f0fef23b6fd/raw/a1b617d5c446b7b41c43e1af96379e3232c4783f/email_report.html) and place it at the path:
__~/Library/Application Support/AutoPkgr/email_report.html__

Then kick off an AutoPkg run using the AutoPkgr menu icon (looks like a suitcase in the menu bar). Let me know if the JSS notifications return.

Thanks!

**Comment by chilcote** [comment] 2016-03-10 22:57
Only difference is the font size went to 12 from 15.

**Comment by homebysix** [comment] 2016-03-10 23:02
@eahrold - Do you think this is related to the selective notifications? Seems possibly related to #507.

**Comment by amandaw33** [comment] 2016-03-11 18:01
Piping in here to say I'm seeing what @chilcote  is seeing - both issues above I have too.  Let me know if I can test anything here.  Thanks for the slack mention pointing me here @homebysix

**Comment by eahrold** [comment] 2016-03-11 18:22
@homebysix most definitely. It really looks like some aren't puttin out expected value in the _summary_results, how do yours look? Are you using the default template?

**Comment by eahrold** [comment] 2016-03-11 18:23
But not selective notifications related. Most likely template related.

**Comment by homebysix** [comment] 2016-03-11 18:31
If it's template related, then putting [email_report.html](https://gist.githubusercontent.com/homebysix/452d9ad78f0fef23b6fd/raw/a1b617d5c446b7b41c43e1af96379e3232c4783f/email_report.html) in the folder above should allow us to troubleshoot. I'm looking through that file and don't see any obvious typos or missing brackets. Do you see anything?

**Comment by eahrold** [comment] 2016-03-11 18:40
I really haven't seen a report.plist with the jss_import_summary_results lately, someone who's having this issue can you gist us the report?

**Comment by amandaw33** [comment] 2016-03-11 18:46
I put email_report.html in the location and ran autopkgr.  Email looked the same to me. happy to do what @eahrold  is asking if someone can point me in the right direction.

**Comment by homebysix** [comment] 2016-03-11 19:06
@chilcote Open up Terminal and enter this:
```
open ${TMPDIR}/com.lindegroup.AutoPkgr/
```
A folder will open and you'll see the report plists, which show the results of the last few AutoPkg runs. If you still have the report associated with the email you received above, we'd love to inspect its contents (via Gist or pasted inline, either works).

Make sure to remove any confidential info first, of course. Thanks!

@amandaw33 If you want to follow the same steps and send us a report plist and its matching email notification, that would be great too. Thanks!

**Comment by amandaw33** [comment] 2016-03-11 19:13
[20160311134335.txt](https://github.com/lindegroup/autopkgr/files/169787/20160311134335.txt)

> 
The following packages were copied:
/Users/jss/Library/AutoPkg/Cache/local.jss.Adobe Acrobat DC/Adobe Acrobat DC-15.010.20060.pkg
/Users/jss/Library/AutoPkg/Cache/local.jss.OracleJava8/OracleJava8-1.8.73.02.pkg
/Users/jss/Library/AutoPkg/Cache/local.jss.AdobeFlashPlayer/AdobeFlashPlayer-21.0.0.182.pkg
/Users/jss/Library/AutoPkg/Cache/local.jss.Adobe Shockwave Player/Adobe Shockwave Player-12.2.4r194.pkg
The following changes were made to the JSS:
This report was generated by AutoPkgr

**Comment by homebysix** [comment] 2016-03-11 19:22
I think I'm able to replicate this issue myself. Here's an example report plist:
[20160311105225.txt](https://github.com/lindegroup/autopkgr/files/169800/20160311105225.txt)

And here's the body of the resulting email:
[email.txt](https://github.com/lindegroup/autopkgr/files/169801/email.txt)

There's clearly a JSSImporter summary result in the plist, but not in the email. Also, there are a lot of `=20`s in the email. Could this be a line-ending problem?

For comparison, here's the JSSImporter summary result from an old AutoPkgr 1.3.2 email:
```
<h3>The following changes were made to the JSS:</h3>
<table>
    <tr><th>Package</th><th>Categories</th><th>Groups</th><th>Scripts</th><=
th>Extension Attributes</th><th>Policy</th><th>Icon</th></tr>
    <tr><td></td><td></td><td></td><td></td><td></td><td>Syncplicity</td><t=
d></td></tr>
    <tr><td></td><td></td><td></td><td></td><td>OracleJavaVersion</td><td>O=
racleJava8</td><td></td></tr>
    <tr><td></td><td></td><td></td><td></td><td>SkypeVersion</td><td>Skype<=
/td><td></td></tr>
    <tr><td></td><td></td><td></td><td></td><td></td><td>Firefox</td><td></=
td></tr>
</table>
```

Elliot

**Comment by homebysix** [comment] 2016-03-11 20:17
It looks like this bug is also affecting Munki summary results. Here's a section of the report plist:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>failures</key>
	<array/>
	<key>summary_results</key>
	<dict>
		<key>munki_importer_summary_result</key>
		<dict>
			<key>data_rows</key>
			<array>
				<dict>
					<key>catalogs</key>
					<string>testing</string>
					<key>name</key>
					<string>1Password</string>
					<key>pkg_repo_path</key>
					<string>apps/1Password-6.1.dmg</string>
					<key>pkginfo_path</key>
					<string>apps/1Password-6.1.plist</string>
					<key>version</key>
					<string>6.1</string>
				</dict>
			</array>
			<key>header</key>
			<array>
				<string>name</string>
				<string>version</string>
				<string>catalogs</string>
				<string>pkginfo_path</string>
				<string>pkg_repo_path</string>
			</array>
			<key>summary_text</key>
			<string>The following new items were imported into Munki:</string>
		</dict>
```

And here's a section of the resulting email:
```
            <!-- Imported to Munki -->
            <!-- "report_fields": ["name", "version", "catalogs", "pkginfo_=
path", "pkg_repo_path"] -->
            =20
```

**Comment by chilcote** [comment] 2016-03-11 21:39
@homebysix here's the output after a run: https://gist.github.com/chilcote/e3a181e488b072603b31

Interestingly, I've noticed two more interesting but maybe unrelated things:
1. The automated scheduled runs don't result in an email being sent (I can only get the email if I run it manually).
2. When run manually, I get an email even if there are no new pkgs to report (see the original screenshot; none of those pkgs were new).

**Comment by homebysix** [comment] 2016-03-11 22:48
@eahrold - I think I tracked down the source of the bug. Check out [this section](https://github.com/lindegroup/autopkgr/blob/issue-508-hotfix/AutoPkgr/Models/Email%20%26%20Notifications/LGAutoPkgReport.m#L423-L457). If I skip the `if (_reportedItemFlags == kLGReportItemsAll)` conditional and simply do `[itemArray addObject:key];` the problem seems to be fixed:

![screen shot 2016-03-11 at 2 39 19 pm](https://cloud.githubusercontent.com/assets/7801391/13717539/17d3fb76-e797-11e5-84fd-ab6b411e1d38.png)

Obviously the conditional notifications are important, so the true solution will more subtle than that.

**Comment by eahrold** [comment] 2016-03-16 01:48
@homebysix I just pushed a commit up to 1.4.1 branch... https://github.com/lindegroup/autopkgr/commit/ae9b660f83a9fc213b7cdcd3a80677090a8e26c7 give it a try when you get a chance.

**Comment by homebysix** [comment] 2016-03-16 06:11
@eahrold Looks better for sure! I got all of the expected output for downloads, munki, pkg, errors, and failures.

However, it's still missing data from `jss_importer_summary_result`:

__Report plist__
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>failures</key>
	<array/>
	<key>summary_results</key>
	<dict>
		<key>jss_importer_summary_result</key>
		<dict>
			<key>data_rows</key>
			<array>
				<dict>
					<key>Categories</key>
					<string></string>
					<key>Extension Attributes</key>
					<string></string>
					<key>Groups</key>
					<string>1Password-update-smart</string>
					<key>Icon</key>
					<string></string>
					<key>Package</key>
					<string></string>
					<key>Policy</key>
					<string>Install Latest 1Password</string>
					<key>Scripts</key>
					<string></string>
				</dict>
			</array>
			<key>header</key>
			<array>
				<string>Package</string>
				<string>Categories</string>
				<string>Groups</string>
				<string>Scripts</string>
				<string>Extension Attributes</string>
				<string>Policy</string>
				<string>Icon</string>
			</array>
			<key>summary_text</key>
			<string>The following changes were made to the JSS:</string>
		</dict>
[...etc...]
```

__Resulting email__
<img width="763" alt="screen shot 2016-03-15 at 11 08 19 pm" src="https://cloud.githubusercontent.com/assets/7801391/13803602/1c940826-eb03-11e5-8b93-a145a89dd17b.png">

**Comment by eahrold** [comment] 2016-03-16 12:12
This may be a jssimporter issue. It looks like  the package name is actually in the policy key,

**Comment by homebysix** [comment] 2016-04-11 16:48
I think we've got this fixed for 1.4.1, release date TBD.

**Comment by homebysix** [comment] 2016-05-02 17:29
1.4.1 has been released. If you were experiencing this problem, please upgrade. Thanks!

**Comment by chilcote** [comment] 2016-05-03 17:04
Thanks @homebysix and crew!

**Comment by amandaw33** [comment] 2016-05-11 11:44
still no email notifications for me. I upgraded to 1.4.1 last week.  Let me know if you want any info from me.  Test email works. I have it set to report all events.

**Comment by chilcote** [comment] 2016-05-11 18:28
Yeah, same.  When I ran it manually I got an email notification, but haven't received any since, regardless of whether it's grabbing new stuff.  Moving back to pre-1.4.

**Comment by mikevmeyer** [comment] 2016-05-17 04:02
Same here... the keychain issue still persists, I believe... some console output when launching preferences reveals this:

5/16/16 8:54:26.023 PM	com.lindegroup.AutoPkgr.helper[80447]	 securityd_message_with_reply_sync Failed to talk to secd after 4 attempts.
5/16/16 8:54:26.023 PM	com.lindegroup.AutoPkgr.helper[80447]	 SecOSStatusWith error:[-25291] Error Domain=com.apple.security.xpc Code=3 "<connection: 0x7fc578f013c0> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid" UserInfo={NSDescription=<connection: 0x7fc578f013c0> { name = com.apple.securityd.xpc, listener = false, pid = 0, euid = 4294967295, egid = 4294967295, asid = 4294967295 }: Connection invalid}
5/16/16 8:54:26.043 PM	com.lindegroup.AutoPkgr.helper[80447]	Sending keychain key to AutoPkgr.
5/16/16 8:54:26.059 PM	secd[506]	 securityd_xpc_dictionary_handler AutoPkgr[80446] copy_matching Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}
5/16/16 8:54:26.059 PM	AutoPkgr[80446]	 SecOSStatusWith error:[-34018] Error Domain=NSOSStatusErrorDomain Code=-34018 "client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={NSDescription=client has neither application-identifier nor keychain-access-groups entitlements}

Thoughts?

I've also noticed that the port test on the notifications tab does not auto-run, like the folders & integrations take, where AutoPkgr auto checks integrations (i.e., JSS Importer, etc.)... I think that the port test should happen automatically, but it's not (at least that's what I would expect it to do). Instead, if I renter the value in the port text box, then hit enter, it then runs the port check.

**Comment by homebysix** [comment] 2016-05-18 00:00
@mikevmeyer - The `client has neither application-identifier nor keychain-access-groups entitlements` you're seeing is normal, and shouldn't prevent notifications from being sent. Please open a separate issue for the port test suggestion, and for any further keychain issues you notice. I'd like to keep this thread solely about email notifications.

@amandaw33 and @chilcote, I can't remember whether I had you try this yet:

- Reinstall the AutoPkgr helper tool. You can do this by holding __Option__ while clicking on the AutoPkgr icon in the menu bar, then clicking __Reinstall Helper Tool__. You will be prompted twice for your password.
- Reload the schedule LaunchDaemon. Easiest way to do this is to uncheck the __Enable scheduled AutoPkg runs__ box, then recheck it. Enter your password when prompted.
- Make sure your SMTP settings are correct (if you can send a test email, you're good).
- Make sure the __which actions trigger notification__ option is set to __Report All Items__ (temporarily).
- Delete one cached package from ~/Library/AutoPkg/Cache, to make sure that the next run will have something to report.

After you do that, check the system logs (filter in Console.app for "AutoPkgr") after the next scheduled run time and see whether anything interesting happened. Also check the most recent report plist (accessible from `open ${TMPDIR}/com.lindegroup.AutoPkgr/`).

I haven't been able to reproduce the email notification failures myself, so this one is tricky for me to isolate. I'll keep this issue open for now, and I'll try running in a few VMs to see whether I can get it to fail.

**Comment by amandaw33** [comment] 2016-05-18 13:20
Thanks for replying, @homebysix 
Reinstall the AutoPkgr helper tool.  - done
Reload the schedule LaunchDaemon - done
Test email - done, email came through but Autopkgr UI still reports "a stable connection to the server could not be established"
Delete one cached package - done, I deleted all chrome .pkgs I had

Scheduled update for 9am.  Console doesn't report anything strange, chrome was downloaded as expected.  No email.  Here's the report plist contents

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>failures</key>
	<array/>
	<key>summary_results</key>
	<dict>
		<key>jss_importer_summary_result</key>
		<dict>
			<key>data_rows</key>
			<array>
				<dict>
					<key>Categories</key>
					<string></string>
					<key>Extension Attributes</key>
					<string>OracleJavaVersion</string>
					<key>Groups</key>
					<string>Auto-OracleJava8-update-smart</string>
					<key>Icon</key>
					<string></string>
					<key>Package</key>
					<string></string>
					<key>Policy</key>
					<string>Auto Update OracleJava8</string>
					<key>Scripts</key>
					<string></string>
				</dict>
				<dict>
					<key>Categories</key>
					<string></string>
					<key>Extension Attributes</key>
					<string></string>
					<key>Groups</key>
					<string>Auto-GoogleChrome-update-smart</string>
					<key>Icon</key>
					<string></string>
					<key>Package</key>
					<string></string>
					<key>Policy</key>
					<string>Auto Update GoogleChrome</string>
					<key>Scripts</key>
					<string></string>
				</dict>
				<dict>
					<key>Categories</key>
					<string></string>
					<key>Extension Attributes</key>
					<string>AdobeFlashVersion</string>
					<key>Groups</key>
					<string>Auto-AdobeFlashPlayer-update-smart</string>
					<key>Icon</key>
					<string></string>
					<key>Package</key>
					<string></string>
					<key>Policy</key>
					<string>Auto Update AdobeFlashPlayer</string>
					<key>Scripts</key>
					<string></string>
				</dict>
				<dict>
					<key>Categories</key>
					<string></string>
					<key>Extension Attributes</key>
					<string>Adobe Shockwave Player</string>
					<key>Groups</key>
					<string>Auto-Adobe Shockwave Player-update-smart</string>
					<key>Icon</key>
					<string></string>
					<key>Package</key>
					<string></string>
					<key>Policy</key>
					<string>Auto Update Adobe Shockwave Player</string>
					<key>Scripts</key>
					<string></string>
				</dict>
			</array>
			<key>header</key>
			<array>
				<string>Package</string>
				<string>Categories</string>
				<string>Groups</string>
				<string>Scripts</string>
				<string>Extension Attributes</string>
				<string>Policy</string>
				<string>Icon</string>
			</array>
			<key>summary_text</key>
			<string>The following changes were made to the JSS:</string>
		</dict>
		<key>pkg_copier_summary_result</key>
		<dict>
			<key>data_rows</key>
			<array>
				<dict>
					<key>pkg_path</key>
					<string>/Users/admin/Library/AutoPkg/Cache/local.jss.OracleJava8/OracleJava8-1.8.91.14.pkg</string>
				</dict>
				<dict>
					<key>pkg_path</key>
					<string>/Users/admin/Library/AutoPkg/Cache/local.jss.AdobeFlashPlayer/AdobeFlashPlayer-21.0.0.242.pkg</string>
				</dict>
				<dict>
					<key>pkg_path</key>
					<string>/Users/admin/Library/AutoPkg/Cache/local.jss.Adobe Shockwave Player/Adobe Shockwave Player-12.2.4r194.pkg</string>
				</dict>
			</array>
			<key>header</key>
			<array>
				<string>pkg_path</string>
			</array>
			<key>summary_text</key>
			<string>The following packages were copied:</string>
		</dict>
		<key>pkg_creator_summary_result</key>
		<dict>
			<key>data_rows</key>
			<array>
				<dict>
					<key>identifier</key>
					<string>com.google.Chrome</string>
					<key>pkg_path</key>
					<string>/Users/admin/Library/AutoPkg/Cache/local.jss.GoogleChrome/GoogleChrome-50.0.2661.102.pkg</string>
					<key>version</key>
					<string>50.0.2661.102</string>
				</dict>
			</array>
			<key>header</key>
			<array>
				<string>identifier</string>
				<string>version</string>
				<string>pkg_path</string>
			</array>
			<key>summary_text</key>
			<string>The following packages were built:</string>
		</dict>
	</dict>
</dict>
</plist>
`

**Comment by chilcote** [comment] 2016-05-18 17:10
I did the same as @amandaw33 
- Reinstalled the helper tool
- Reloaded the LaunchDaemon
- Sent a successful test email
- Deleted everything under the Chrome cache folder

The job ran, it processed Chrome, but I never got an email. 

Plist: https://gist.github.com/chilcote/5ddf9e96b81ca9d13ffc95a5a0fe8d9e

Thanks,
--joe

**Comment by homebysix** [comment] 2016-05-20 03:55
@chilcote and @amandaw33, what's the output when you run this command?

```
defaults read com.lindegroup.AutoPkgr reportedItemFlags
```

**Comment by chilcote** [comment] 2016-05-20 04:37
`The domain/default pair of (/Users/autopkgr/Library/Preferences/com.lindegroup.AutoPkgr, reportedItemFlags) does not exist`

**Comment by homebysix** [comment] 2016-05-20 05:06
@chilcote I think I've finally tracked this down. Open up the __Choose which actions trigger notification__ settings and flip to "Report Some Items," and then back to "Report All Items" again. Then let the next scheduled run happen and let me know whether you get an email notification. (You can delete something from the cache if you want to force the notification to occur.)

More details including reproduction steps in #533.

**Comment by chilcote** [comment] 2016-05-20 05:09
Gotcha, will do.

```
$ defaults read com.lindegroup.AutoPkgr reportedItemFlags
1
```

**Comment by chilcote** [comment] 2016-05-20 17:18
Looks good @homebysix. I got the notification today. Nice detective work.

**Comment by mikevmeyer** [comment] 2016-05-22 04:49
Sorry, I followed the steps in #533 but I'm still not receiving emails.

**Comment by amandaw33** [comment] 2016-05-24 15:12
@homebysix  - sorry I've been out of the office.  I confirmed when I ran

defaults read com.lindegroup.AutoPkgr reportedItemFlags

I got does not exist like @chilcote  above.  I went in and toggled the choose which actions to toggle and then went back to all items and now when I run above command I get return value of 3.

Deleted chrome, allowed scheduled run to go and no email.

Thanks for your help. Let me know if I can test anything else.

**Comment by chilcote** [comment] 2016-05-25 03:39
@amandaw33 Mine had a value of 1, maybe there's a distinction there?

@homebysix I've noticed since I've started getting notifications again, I get notifications even if no new packages are added to JSS.

I only have these checked in notification triggers:
- New software imported into...
- Errors
- Update to integrated tools

I get emails like this. Related to this bug?

<img width="520" alt="screen shot 2016-05-24 at 8 35 49 pm" src="https://cloud.githubusercontent.com/assets/305026/15527450/7e527b74-21ef-11e6-8250-7733f1836f44.png">

**Comment by homebysix** [comment] 2016-05-25 16:10
@mikevmeyer - I'm not sure that you're experiencing the same issues as the others, since your initial post was entirely about keychain issues. Find me in the MacAdmins Slack team if you have a few minutes and I'll give you some steps to try in real time.

@chilcote JSS recipes will inherently make changes every time they run (e.g. updating policies and smart groups), and right now the "New software imported into..." option does not care which changes are made, so it reports after every run. I get around that by unchecking "New software imported into..." and checking "New package is built" instead (since all JSS recipes are based on pkg recipes). Like so:
![screen shot 2016-05-25 at 8 47 48 am](https://cloud.githubusercontent.com/assets/7801391/15546616/69e2a3ce-2255-11e6-899b-f74a7e4af92f.png)
Additionally, AutoPkgr doesn't currently display changes to extension attributes in the notifications, even though extension attributes _are_ among the things that can trigger a notification to be sent. There's a complicated reason for that, which will be fixed soon after [this JSSImporter PR](https://github.com/sheagcraig/JSSImporter/pull/83) is merged. But that may explain the blank email you received.

@amandaw33 I'm doing some testing with the value set to `3` and I'll have more information shortly. Thanks!

**Comment by chilcote** [comment] 2016-05-25 17:04
Thanks @homebysix 👍

**Comment by mikevmeyer** [comment] 2016-05-25 19:40
Thanks @homebysix, I'll track you down on Slack!

**Comment by amandaw33** [comment] 2016-05-26 15:04
@homebysix  I just got a scheduled notification email that Chrome downloaded.  Not sure why I didn't get before but maybe I'm fixed after all?

**Comment by homebysix** [comment] 2016-05-26 17:23
@amandaw33 I wasn't able to reproduce any problems with my `reportedItemFlags` set to `3`, so it might be that you are fixed. 🍀 

If you don't want to wait until the next scheduled run, you can force it to happen by doing this:

```
sudo defaults write /Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist RunAtLoad -bool true
```

Then delete Chrome from your AutoPkg cache and kick off a scheduled run:
```
sudo launchctl unload /Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist
sudo launchctl load /Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist
```

See if your notifications arrive after doing that.

Once everything looks good, you can reset the schedule LaunchDaemon by doing this:
```
sudo defaults delete /Library/LaunchDaemons/com.lindegroup.AutoPkgr.schedule.plist RunAtLoad
```

**Comment by amandaw33** [comment] 2016-05-27 14:20
@homebysix  that test worked as well.  considered my issue resolved.  thanks for the followup, as always. have a good holiday.

**Comment by homebysix** [comment] 2016-05-27 18:28
Excellent! Thanks all.

**Closed by homebysix** 2016-05-27 18:28 UTC
Labels: bug
