### ISSUE TITLE
Repeated "Update to helper components available" Notification Emails

### ISSUE THREAD

**Issue by foigus** [lindegroup/autopkgr#379] opened 2015-07-18 17:37 UTC
Ever since AutoPkg .50 went live, it appears that AutoPkgr is emailing a notification about that release with every AutoPkgr run.

Note I also received a single notification I received about the actual AutoPkg AutoPkg recipe, so it doesn't appear to be that recipe that's the issue.

**Comment by franton** [comment] 2015-07-18 17:39
Confirmed. I am seeing this every time AutoPkgr is scheduled to run on my work machine. That's three now for every six hours it's run.

**Comment by eahrold** [comment] 2015-07-18 18:25
@foigus, @franton 
This is the current expected behavior since it's simply a routine run at the end of each schedule, but maybe we should handle it with a little more finesse. It'd easy enough to set it up to only send notifications once each new version.

I sort of like being nagged to update, but can see how that's not for everyone.

So once notification per new version sound like a better approach to you?
Votes - Thoughts?

**Comment by franton** [comment] 2015-07-18 18:28
Hi Eldon,

That sounds perfectly acceptable to me. However I normally have AutoPkgR’s emails go into their own email folder. I think I need to revise my email rules as the emails sent in this instance went straight into my inbox instead.

**Comment by eahrold** [comment] 2015-07-18 18:29
Because you were filtering by subject string?

**Comment by franton** [comment] 2015-07-18 18:31
Yes. I'd check and confirm but it's a national holiday for the next five days starting today so no access to the office. I guess i'm putting up with this for a few days!

**Comment by foigus** [comment] 2015-07-19 03:56
Possibly consider emailing every couple days or once a week?  I have AutoPkgr running three times a day fwiw.

**Comment by eahrold** [comment] 2015-07-19 16:34
@foigus good call, I like the idea of once a week even better.

**Comment by futureimperfect** [comment] 2015-07-19 18:47
@eahrold I like this idea too, although it should probably be customizable.

-- 
James Barclay

**Comment by eahrold** [comment] 2015-07-19 19:10
@futureimperfect What are you thinking for options? Include an every time op?

**Comment by futureimperfect** [comment] 2015-07-19 20:15
Yeah, or default to notifying every run and allow users to tune how often they get notified for any given update.

-- 
James Barclay

**Comment by homebysix** [comment] 2015-07-19 22:14
I agree customization would be great, but let's default to once per week. We want "maximum annoying" to be opt-in, not opt-out. :-)

**Comment by eahrold** [comment] 2015-07-19 22:26
Agreed. Here's what I'm thinking now...

- One time only
- Once a week (default)
- Once a day

**Comment by eahrold** [comment] 2015-07-19 22:56
Where should we park the UI Elements?

It seems like a "Notification" type, but _could_ be considered a "Schedule" type (and there's more room there).

**Comment by homebysix** [comment] 2015-07-20 16:57
I agree it should be in the Notifications tab, and that's tricky because the Notifications tab is running out of space. We could do something like this, with "Configure..." leading to the once/daily/weekly options mentioned above.

![screen shot 2015-07-20 at 9 45 30 am](https://cloud.githubusercontent.com/assets/7801391/8781496/3946c25c-2ec4-11e5-891f-7a8397964534.png)

But that adds an extra click and obfuscates a setting that should be visible at a glance.

Or we could just make the window bigger:
![screen shot 2015-07-20 at 9 50 50 am](https://cloud.githubusercontent.com/assets/7801391/8781592/d47f6f26-2ec4-11e5-9ced-29aaed3291c0.png)

I'm on the fence but leaning towards the Configure button as a short term solution and dynamic tab sizing as the long term solution.

**Comment by poundbangbash** [comment] 2015-07-20 17:06
If the options are just going to be once/daily/weekly would a popup menu in place of the Configure button make sense?
If it’s going to be able to be customized more like the Schedule tab options then the expanded window would be fine or dynamically expand it when the box is checked.  For me, I expanded the window larger than default to see the recipes and repos on the other tab.   Since the window size stays that big between tabs there is extra room on my setup, but of course others may vary.

I’d also suggest either having a hover/popup explaining what “component tools” are or including that in the verbiage “…to component tools (e.g. AutoPkg, git, munch tools) are available…”

-Eric

**Comment by eahrold** [comment] 2015-07-20 17:35
I just pushed a branch. I opted for the popup for both space and because it kept the code more concise.
I agree we should probably do something more specific with the language, I'm open to suggestions...

https://github.com/lindegroup/autopkgr/tree/integration-frequency

![frequency](https://cloud.githubusercontent.com/assets/3740088/8782384/a8987ac2-2eda-11e5-874f-1c9d12e2bee5.png)

**Comment by homebysix** [comment] 2015-07-20 17:36
This looks good! I'll test it out.

You can ignore my branch. Yours is better.

**Comment by eahrold** [comment] 2015-07-20 18:01
And one last detail as to the current "expected" behavior.

If the _only_ thing available is an integration update, it will report based on the set frequency, however if some other element is causing a report to get sent, such as a new download or an error, the integration update information will be included reported.

Does that sound sensible?

**Comment by homebysix** [comment] 2015-07-20 18:18
That sounds sensible to me. I'll clarify that in the UI.

**Closed** 2015-07-24 17:17 UTC
