### ISSUE TITLE
Filewave error

### ISSUE THREAD

**Issue by kstoeber** [lindegroup/autopkgr#512] opened 2016-03-17 16:56 UTC
When setting up AutoPkgr I am getting an error message:  too many values to unpack

Do you have any suggestions?

**Comment by homebysix** [comment] 2016-03-17 17:07
Hi @kstoeber, thanks for reporting this.

Could you provide the steps you followed, in order? I'll try to reproduce them on my end.

**Comment by kstoeber** [comment] 2016-03-17 17:17
I have installed AutoPkgr on a OS 10.10.5 with Filewave Admin 10.1.0  I then installed Git, and the FileWaveImporter.  I then selected the Repos & Recipes selected the https://github.com/autopkg/recipes.git and updated.  That indicated ok, so I selected the AdobeFlashPlayer.filewave Recipe and then Run Recipes Now button.  That produced the error.

**Comment by kstoeber** [comment] 2016-03-17 17:18
@homebysix Also when configuring the FileWave Importer I have seen the message when trying to verify.

**Comment by kstoeber** [comment] 2016-03-17 17:28
@homebysix Also if I just use the Filewave recipes I see the following error:

A Python exception occurred during the execution of autopkg, see the system log for more details.  [ERROR] EOFError: EOR when reading a line

**Comment by homebysix** [comment] 2016-03-17 17:29
Thanks @kstoeber, that helps a lot. Could I have you try running this command in Terminal, and paste the output here?
```
autopkg run -v AdobeFlashPlayer.filewave
```

**Comment by kstoeber** [comment] 2016-03-17 17:33
@homebysix 

21573:~ ladmin$ autopkg run -v AdobeFlashPlayer.filewave
Processing AdobeFlashPlayer.filewave...
AdobeFlashURLProvider
AdobeFlashURLProvider: Found URL http://fpdownload.macromedia.com/get/flashplayer/pdc/21.0.0.182/install_flash_player_osx.dmg
URLDownloader
URLDownloader: Item at URL is unchanged.
URLDownloader: Using existing /Users/ladmin/Library/AutoPkg/Cache/com.github.autopkg.filewave.FlashPlayerNoRepackage/downloads/AdobeFlashPlayer.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image /Users/ladmin/Library/AutoPkg/Cache/com.github.autopkg.filewave.FlashPlayerNoRepackage/downloads/AdobeFlashPlayer.dmg
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "Adobe Flash Player.pkg":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Adobe Systems, Inc.
CodeSignatureVerifier:        SHA1 fingerprint: 9D 75 C9 20 01 4A 65 04 94 A7 63 95 E3 91 93 47 04 E8 57 DF
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
Versioner
Versioner: Mounted disk image /Users/ladmin/Library/AutoPkg/Cache/com.github.autopkg.filewave.FlashPlayerNoRepackage/downloads/AdobeFlashPlayer.dmg
Versioner: Found version 21.0.0.182 in file /private/tmp/dmg.RGiLo8/Install Adobe Flash Player.app/Contents/Info.plist
PkgCopier
PkgCopier: Mounted disk image /Users/ladmin/Library/AutoPkg/Cache/com.github.autopkg.filewave.FlashPlayerNoRepackage/downloads/AdobeFlashPlayer.dmg
PkgCopier: Copied /private/tmp/dmg.TQiysJ/Install Adobe Flash Player.app/Contents/Resources/Adobe Flash Player.pkg to /Users/ladmin/Library/AutoPkg/Cache/com.github.autopkg.filewave.FlashPlayerNoRepackage/AdobeFlashPlayer-21.0.0.182.pkg
com.github.autopkg.filewave.FWTool/FileWaveImporter
too many values to unpack
Failed.
Receipt written to /Users/ladmin/Library/AutoPkg/Cache/com.github.autopkg.filewave.FlashPlayerNoRepackage/receipts/AdobeFlashPlayer-receipt-20160317-123148.plist

The following recipes failed:
    AdobeFlashPlayer.filewave
        Error in com.github.autopkg.filewave.FlashPlayerNoRepackage: Processor: com.github.autopkg.filewave.FWTool/FileWaveImporter: Error: too many values to unpack

The following packages were copied:
    Pkg Path                                                                                                                
    --------                                                                                                                
    /Users/ladmin/Library/AutoPkg/Cache/com.github.autopkg.filewave.FlashPlayerNoRepackage/AdobeFlashPlayer-21.0.0.182.pkg

**Comment by homebysix** [comment] 2016-03-17 18:09
Hi @kstoeber — That helps narrow it down. If the error is persisting when running the recipe using the `autopkg` command in Terminal, that means it's not an AutoPkgr issue.

I recommend opening a new issue [here](https://github.com/autopkg/filewave/issues), because there's most likely a bug in the FileWaveImporter processor or AdobeFlashPlayer.filewave recipe. You can paste in a link to this issue, for context.

I'll close this here, but feel free to comment again if you have any questions.

**Closed** 2016-03-17 18:10 UTC
