### ISSUE TITLE
MakeCatalogs.munki recipe sometime missing even when enabled

### ISSUE THREAD

**Issue by Lotusshaney** [lindegroup/autopkgr#657] opened 2020-10-12 08:29 UTC
Autopkgr 1.5.5 sometime when enabling recipes the MakeCatalogs.munki will disappear from recipe_list.txt file, even though the GUI shows it as enabled.  The only way to restore it is to disable and re-enable the MakeCatalogs.munki recipe in the GUI.

This results in packages being downloaded multiple times as the catalogs have not been rebuilt.

for Example:-

./pkgsinfo/apps/Slack-4.10.2__1.plist
./pkgsinfo/apps/Slack-4.10.2__2.plist
./pkgsinfo/apps/Slack-4.10.2__3.plist
./pkgsinfo/apps/Slack-4.10.2__4.plist
./pkgsinfo/apps/Slack-4.10.2__5.plist
./pkgsinfo/apps/Slack-4.10.2__6.plist
./pkgsinfo/apps/Slack-4.10.2__7.plist
./pkgsinfo/apps/Slack-4.10.2__8.plist

Also could the MakeCatalogs.munki be added as the last item in the txt files.  I know there is logic in autopkgr to fudge the txt list but making it the actual list item would help in troubleshooting as you can simply use the txt file with autopkg without the need to edit it.

**Comment by Lotusshaney** [comment] 2020-10-12 08:33
As a sidenote, I have the same problem using an override and the original recipe for MakeCatalogs.munki

**Comment by jby** [comment] 2020-10-12 08:41
This is what it looks like on my machine now, present in the text-file, but **not** selected in the GUI...

<img width="1232" alt="Screenshot 2020-10-12 at 10 34 35" src="https://user-images.githubusercontent.com/1584888/95724951-4b5d9d80-0c77-11eb-8ead-708583b653b6.png">
<img width="636" alt="Screenshot 2020-10-12 at 10 32 59" src="https://user-images.githubusercontent.com/1584888/95724958-50225180-0c77-11eb-9612-f549471c4868.png">

**Comment by Prodeguerriero** [comment] 2020-10-12 14:05
Same here, I have noticed some inconsistent behavior. At first I thought it was because I renamed the override manually (when creating the override I am not given the option to rename it, like for other recipes) but then it happened again with the default naming.

Another thing that might be related. Even though it does look like MakeCatalogs.munki runs (if I try to run it manually from the command line I get `MakeCatalogsProcessor: No need to rebuild catalogs.`), the catalogs don't appear to be updated properly. I need to manually run `makecatalogs` from the command line (or use MunkiAdmin) before my test client machine finds the new packages for download.

**Comment by Lotusshaney** [comment] 2020-10-13 16:49
I get the same problem as @Prodeguerriero too, The MakeCatalogsProcessor reports that there is no need to rebuild the catalogs but unless I do a manual makecatalogs from the command line, munki is not updated and clients do not see the updates

**Comment by Prodeguerriero** [comment] 2020-10-21 17:05
I can confirm that removing **any** recipe from the list in the UI triggers the removal of the MunkiCatalog override from the `.txt` file. To add it again, one needs to uncheck it in the UI and check it again.

**Comment by foigus** [comment] 2020-10-26 17:37
I'm also seeing MakeCatalogs oddities (repeated imports of packages that are newly-discovered by AutoPkg since the last manual "makecatalogs" run).  In my case "local.munki.MakeCatalogs" is the first entry in "recipe_list.txt" and is checked in the AutoPkgr GUI.

**Comment by shawnhonsberger** [comment] 2020-10-27 20:29
Thanks, all. I'll look into this.

**Comment by shawnhonsberger** [comment] 2020-10-27 23:57
Thanks, everyone. I confirmed the issue where MakeCatalogs was removed from the recipe_list when a new recipe was added, due to previous logic. This will need to be corrected, as it behaves as if a user hadn't added MakeCatalogs to their list.

**Comment by shawnhonsberger** [comment] 2020-10-28 16:07
I’ll work to fix this. For now, know that toggling MakeCatalogs off and back on re-adds it to the list. Alternatively, you can manually add it to the end of your list.

**Comment by Prodeguerriero** [comment] 2020-11-04 09:36
Hey @shawnhonsberger,

Thanks for looking into it. While at it, do you think it would be possible to enable renaming for the MakeCatalogs override, like other overrides? Only if it is something you can quickly add, otherwise I can live without it 😛

**Comment by shawnhonsberger** [comment] 2020-12-15 22:26
Hi, everyone. I recently created fixes for these issues, and they'll be coming in a future release of AutoPkgr. Thanks for your patience, and your reporting!

**Comment by DanielWeeber** [comment] 2021-01-11 22:25
Nice, thank you! Waiting for this =)

**Comment by securitygeneration** [comment] 2021-02-08 10:28
Re-checking `MakeCatalogs.munki` adds it to the top of the `recipe_list.txt`, but it needs to be at the bottom no? Otherwise MakeCatalogs runs first, followed by all the other recipes. Also looking forward to the fix for this!

**Comment by apizz** [comment] 2021-02-13 23:43
@securitygeneration you are correct.  Each time I add a new recipe and toggle MakeCatalogs.munki off and on I manually go into the file and reorder to put it at the bottom.

**Comment by shawnhonsberger** [comment] 2021-02-23 22:09
Hi everyone, AutoPkgr 1.5.6 released today should help this issue: https://github.com/lindegroup/autopkgr/releases. utoPkgr will once again automatically add the MakeCatalogs.munki recipe to the end of your recipe list and keep it there. You do not have to check the box to include the MakeCatalogs.munki in your schedule. It will be included automatically.

**Comment by apizz** [comment] 2021-02-23 22:28
Hmmm, so it does not appear that we can uncheck the recipe if already added.  Had to go in manually and remove from the recipe list, quit & reopen AutoPkgr.

**Comment by shawnhonsberger** [comment] 2021-02-23 22:33
Thanks @apizz. That is what I had expected might happen. This reverts to the pre-1.5.5 behavior, where the MakeCatalogs recipe is managed by AutoPkgr. Apologies, for the inconvenience.

**Comment by apizz** [comment] 2021-02-23 22:34
no big deal imho

**Closed** 2021-02-23 23:25 UTC
